# Generated by Django 2.1.3 on 2019-02-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.Service')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(default='09:00', max_length=5)),
                ('endTime', models.CharField(default='14:45', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='calendarconfig',
            name='time',
            field=models.ManyToManyField(to='calendario.CalendarTime'),
        ),
    ]
