# Generated by Django 2.1.3 on 2019-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfig',
            name='slotSize',
            field=models.IntegerField(default=15, verbose_name='Tamaño del huevo en minutos'),
        ),
    ]
