# Generated by Django 2.1.3 on 2019-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_calendarconfig_slotsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarconfig',
            name='slotSize',
            field=models.IntegerField(default=15, verbose_name='Tamaño del hueco en minutos'),
        ),
    ]
