# Generated by Django 2.1.3 on 2019-02-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_calendartime_appointmentsperslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendartime',
            name='appointmentsPerSlot',
        ),
        migrations.AddField(
            model_name='calendarconfig',
            name='appointmentsPerSlot',
            field=models.IntegerField(default=1, verbose_name='Máximo número de citas por tramo'),
        ),
    ]
