# Generated by Django 2.1.3 on 2019-03-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_auto_20190210_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
