# Generated by Django 2.1.3 on 2019-03-08 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_calendarexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarexception',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendario.CalendarTime', verbose_name='Calendario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarexception',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de festivo'),
            preserve_default=False,
        ),
    ]
