# Generated by Django 2.1.3 on 2019-02-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, verbose_name='DNI o NIE (Sin letra)')),
                ('email', models.EmailField(max_length=254, verbose_name='Dirección de correo donde se enviará la confirmación')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de la cita')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceID', models.IntegerField(verbose_name='Número de servicio en el sistema')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
    ]
