# Generated by Django 2.1.3 on 2019-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='weeks_in_advance',
            field=models.IntegerField(default=2, verbose_name='Semanas en las que se puede reservar con antelación'),
        ),
    ]
