# Generated by Django 2.1.3 on 2019-02-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_service_weeks_in_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hota',
            field=models.TimeField(default='09:00', verbose_name='Hora de la cita'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de la cita'),
        ),
    ]
