# Generated by Django 2.1.3 on 2019-02-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20190210_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='hota',
            new_name='hora',
        ),
    ]
