# Generated by Django 2.1.3 on 2019-02-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_auto_20190210_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_id',
            field=models.IntegerField(default=2, verbose_name='Número de servicio en el sistema'),
        ),
    ]
