# Generated by Django 2.1.3 on 2019-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_appointment_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceID',
            field=models.BigIntegerField(verbose_name='Número de servicio en el sistema'),
        ),
    ]
