# Generated by Django 2.1.3 on 2019-03-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_auto_20190311_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_id',
            field=models.BigIntegerField(default=2, verbose_name='Número de servicio en el sistema'),
        ),
    ]
